(define (install-scheme-numbers)
    (define (tag contents)
        (attach-tag 'scheme-number contents))

    (define (raise-to-rational number)
        (make-rational-number number
                               1))

    (put 'add '(scheme-number scheme-number) (lambda (a b) (tag (+ a b))))
    (put 'sub '(scheme-number scheme-number) (lambda (a b) (tag (- a b))))
    (put 'mul '(scheme-number scheme-number) (lambda (a b) (tag (* a b))))
    (put 'div '(scheme-number scheme-number) (lambda (a b) (tag (/ a b))))
    (put 'make 'scheme-number (lambda (num) (tag num)))
    (put-coercion 'scheme-number 'complex (lambda (n) (make-from-real-imag (contents n)
                                                                           0)))
    (put-coercion 'rational 'scheme-number (lambda (rational-num) (tag (/ (car (contents rational-num))
                                                                          (cdr (contents rational-num))))))
    (put 'raise '(scheme-number) (lambda(integer) (raise-to-rational integer)))
    (display "Installed scheme numbers...")
    (newline))
