(define (install-sparse-termlist)
    (define (sparse-make-term order coefficient) (list order coefficient))
    (define (sparse-order term) (car (car term)))
    (define (sparse-coeff term) (cadr (car term)))
    (define (sparse-adjoin-term term term-list) (if (=zero? (sparse-coeff term)) term-list (cons (car term) term-list)))
    (put 'order 'sparse sparse-order)
    (put 'coeff 'sparse sparse-coeff)
    (put 'adjoin-term 'sparse sparse-adjoin-term)
    (put 'make-term 'sparse sparse-make-term)
)
